apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  type: LoadBalancer  # Use LoadBalancer for cloud environments or NodePort for on-prem/local clusters
  ports:
    - port: 80            # External port (HTTP)
      targetPort: 3000     # Grafana's internal port
      protocol: TCP
  selector:
    app: grafana
