apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: LoadBalancer
  ports:
  - port: 80           # External port for access
    targetPort: 8080   # Port that Jenkins is listening on within the Pod
    protocol: TCP
  selector:
    app: jenkins       # This should match the label of your Jenkins Pods
