apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080  # Default port for Jenkins
        # If you want to configure Jenkins without SSL
        env:
        - name: JENKINS_OPTS
          value: "--httpPort=8080 --httpListenAddress=0.0.0.0"
